name: WeChat Push

on:
  schedule:
    - cron: '0 23 * * *'  # 每天早上7:00 UTC+8 运行
    - cron: '50 5 * * 1'   # 每周一13:50 UTC+8 运行
  workflow_dispatch:       # 支持手动触发

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Update main.py with secrets
        run: |
          sed -i 's/^appID = ""/appID = "${{ secrets.APP_ID }}"/' main.py
          sed -i 's/^appSecret = ""/appSecret = "${{ secrets.APP_SECRET }}"/' main.py
          sed -i 's/^openId = ""/openId = "${{ secrets.OPEN_ID }}"/' main.py
          sed -i 's/^weather_template_id = ""/weather_template_id = "${{ secrets.TEMPLATE_ID }}"/' main.py
          sed -i 's/^timetable_template_id = ""/timetable_template_id = "${{ secrets.WECHAT_TIMETABLE_TEMPLATE_ID }}"/' main.py
          
      - name: Run push script
        run: |
          python main.py
